dataset:
    name: pascal3d
    class_name: dataset.Pascal3DPlus
    root_path: data/OOD_CV
    sampler: None
    transforms:
        - class_name: dataset.ToTensor
model:
    name: resnet50
    class_name: src.models.resnet.ResNetGeneral
    output_dim: 123
    num_bins: 41
    backbone: resnet50
    transforms:
        - class_name: dataset.Resize
          height: 256
          width: 256
        - class_name: dataset.Normalize
    training:
        loss:
            class_name: torch.nn.CrossEntropyLoss
            ignore_index: 41
        optimizer:
            class_name: torch.optim.SGD
            lr: 0.01
            momentum: 0.9
            weight_decay: 0.0001
        scheduler:
            class_name: torch.optim.lr_scheduler.StepLR
            step_size: 20
            gamma: 0.1

task: 3d_pose_estimation

training:
    batch_size: 32
    workers: 8
    total_epochs: 90
    log_interval: 1
    ckpt_interval: 30
    scale_iterations_per_epoch: 1.0

inference:
